/*************************************************************************
 *                                                                       *
 * polyjam, a polynomial solver generator for C++                        *
 * Copyright (C) 2015 Laurent Kneip, The Australian National University  *
 *                                                                       *
 * This program is free software: you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation, either version 3 of the License, or     *
 * (at your option) any later version.                                   *
 *                                                                       *
 * This program is distributed in the hope that it will be useful,       *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 * GNU General Public License for more details.                          *
 *                                                                       *
 * You should have received a copy of the GNU General Public License     *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. *
 *                                                                       *
 *************************************************************************/

//This code is automatically generated by polyjam for solving faP4P.
//It is licensed under the GNU GPL terms.
//Please contact the author of polyjam for proprietary use.

#ifndef FAP4P
#define FAP4P

#include <stdlib.h>
#include <Eigen/Eigen>
#include <vector>


namespace polyjam
{
namespace faP4P
{
  Eigen::Matrix3d composeB( std::vector< Eigen::Vector3d> & x );
  Eigen::Matrix3d composeG( std::vector< Eigen::Vector3d> & X );
  Eigen::Matrix3d getA( Eigen::Matrix3d & G );

  void createCoeffs( Eigen::Matrix3d & A, Eigen::Matrix3d & B,
                     Eigen::Matrix3d & A1, Eigen::Vector3d & b1, double & c1,
                     Eigen::Matrix3d & A2, Eigen::Vector3d & b2, double & c2,
                     Eigen::Matrix3d & A3, Eigen::Vector3d & b3, double & c3 );

  void solve( std::vector< Eigen::Vector3d> & x, std::vector< Eigen::Vector3d> & X, std::vector<Eigen::Matrix<double,3,7> > & S );

}
}

#endif